# Site settings
title: Jekyll Weekly
description: A free, once-a-week round-up of Jekyll news and articles.
baseurl: ""
url: http://jekyllweekly.com

# Jekyll configuration
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
encoding: utf-8

# SASS settings
sass:
  sass_dir: _sass
  style: compressed

# Gems
gems:
  - jekyll-feed

include: ["_pages"]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "gulpfile.js", "package.json"]
